# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "boxcutter/ubuntu1404-desktop"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
   config.vm.provider "virtualbox" do |vb|
     # Display the VirtualBox GUI when booting the machine
     vb.gui = true
     vb.name = "TestFul"
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
   end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Define a Vagrant Push strategy for pushing to Atlas. Other push strategies
  # such as FTP and Heroku are also available. See the documentation at
  # https://docs.vagrantup.com/v2/push/atlas.html for more information.
  # config.push.define "atlas" do |push|
  #   push.app = "YOUR_ATLAS_USERNAME/YOUR_APPLICATION_NAME"
  # end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
   config.vm.provision "shell", inline: <<-SHELL

     sudo apt-get update
     sudo apt-get install -y openjdk-7-jre
     sudo apt-get install -y openjdk-7-jdk
    
     sudo touch login_desktop.sh
     sudo echo "#! /bin/bash" >> login_desktop.sh
     sudo echo "/usr/bin/gsettings set org.gnome.desktop.screensaver lock-enabled false" >> login_desktop.sh
     sudo chmod 777 login_desktop.sh

     sudo touch login_desktop.sh.desktop
     sudo echo "[Desktop Entry]" >> login_desktop.sh.desktop
     sudo echo "Type=Application" >> login_desktop.sh.desktop
     sudo echo "Exec=/home/vagrant/login_desktop.sh" >> login_desktop.sh.desktop
     sudo echo "Hidden=false" >> login_desktop.sh.desktop
     sudo echo "NoDisplay=false" >> login_desktop.sh.desktop
     sudo echo "X-GNOME-Autostart-enabled=true" >> login_desktop.sh.desktop
     sudo echo "Name=LockScreen Disabled" >> login_desktop.sh.desktop
     sudo echo "Comment=Disable the lock screen" >> login_desktop.sh.desktop
     sudo chmod 777 /home/vagrant/login_desktop.sh.desktop
     sudo update-desktop-database
     sudo cp login_desktop.sh.desktop /etc/xdg/autostart/login_desktop.sh.desktop
     
     
     cd /home/vagrant/Desktop
     sudo wget "https://googledrive.com/host/0B4H6x7rqcFw3Q2RrZ1QxdWE5Zk0/TestFul_Workspace.tar.gz"
     tar -zxvf TestFul_Workspace.tar.gz
     
     

     # Create an application launcher for Eclipse (to launch it on startup)
     sudo chmod 777 /home/vagrant/Desktop/eclipse.desktop
     sudo update-desktop-database
     rm TestFul_eclipseproject.*

     cd /home/vagrant/.config/
     mkdir autostart
     sudo cp /home/vagrant/Desktop/eclipse.desktop /home/vagrant/.config/autostart/
     
     # Remove unused icons from sidebar (making VM as minimal as possible)
     sudo rm -f "/usr/share/applications/ubuntu-amazon-default.desktop"
     sudo rm -f "/usr/share/applications/libreoffice-calc.desktop"
     sudo rm -f "/usr/share/applications/libreoffice-writer.desktop"
     sudo rm -f "/usr/share/applications/libreoffice-impress.desktop"
     sudo rm -f "/usr/share/applications/ubuntu-software-center.desktop"

     sudo apt-get install flashplugin-installer
     sudo reboot     
   SHELL
end
